# Generated by Django 5.0.4 on 2024-04-23 10:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('active', models.IntegerField(default=1)),
                ('ip_address', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_year_user', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_year_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Academic_Years',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_semester', models.IntegerField(blank=True, null=True)),
                ('semester_name', models.CharField(blank=True, max_length=255, null=True)),
                ('year_name_g', models.CharField(blank=True, max_length=255, null=True)),
                ('year_name_h', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('finance_year_name', models.CharField(blank=True, max_length=255, null=True)),
                ('finance_start_date', models.DateField(blank=True, null=True)),
                ('finance_end_date', models.DateField(blank=True, null=True)),
                ('number_of_weeks', models.IntegerField(blank=True, null=True)),
                ('admission_on', models.IntegerField(blank=True, default=0, null=True)),
                ('is_default', models.IntegerField(blank=True, default=0, null=True)),
                ('edit_std_status', models.IntegerField(blank=True, default=0, null=True)),
                ('grade_edit', models.IntegerField(blank=True, default=0, null=True)),
                ('week_plan', models.IntegerField(blank=True, default=0, null=True)),
                ('ignore_weekly_pal_dates', models.IntegerField(blank=True, default=0, null=True)),
                ('allow_add_material_cover', models.IntegerField(blank=True, default=0, null=True)),
                ('job_applicant_on', models.IntegerField(blank=True, default=0, null=True)),
                ('allow_to_create_weekly_plan', models.IntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46'), ('47', '47'), ('48', '48'), ('49', '49'), ('50', '50'), ('51', '51'), ('52', '52'), ('53', '53'), ('54', '54'), ('55', '55'), ('56', '56'), ('57', '57'), ('58', '58'), ('59', '59'), ('60', '60')], null=True)),
                ('allow_to_view_weekly_plan', models.IntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46'), ('47', '47'), ('48', '48'), ('49', '49'), ('50', '50'), ('51', '51'), ('52', '52'), ('53', '53'), ('54', '54'), ('55', '55'), ('56', '56'), ('57', '57'), ('58', '58'), ('59', '59'), ('60', '60')], null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('active', models.IntegerField(default=1)),
                ('ip_address', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_academic_user', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_academic_user', to=settings.AUTH_USER_MODEL)),
                ('year_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academic.year')),
            ],
        ),
        migrations.CreateModel(
            name='Academic_Year_Semesters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_semesters', models.IntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], null=True)),
                ('no_of_quarters_each_sem', models.IntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('active', models.IntegerField(default=1)),
                ('ip_address', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_semster_user', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_semster_user', to=settings.AUTH_USER_MODEL)),
                ('year_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academic.year')),
            ],
        ),
    ]
