# Generated by Django 5.0.4 on 2024-05-21 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_alter_academic_year_semesters_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semester',
            old_name='semester_id',
            new_name='academic_year_semester_id',
        ),
    ]
