# Generated by Django 5.0.4 on 2024-06-13 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_remove_semester_academic_year_semester_id_and_more'),
        ('general_settings', '0002_rename_finance_fee_collections_financefeecollections_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academic_years',
            name='admission_on',
        ),
        migrations.RemoveField(
            model_name='academic_years',
            name='allow_add_material_cover',
        ),
        migrations.RemoveField(
            model_name='academic_years',
            name='allow_to_create_weekly_plan',
        ),
        migrations.RemoveField(
            model_name='academic_years',
            name='allow_to_view_weekly_plan',
        ),
        migrations.RemoveField(
            model_name='academic_years',
            name='edit_std_status',
        ),
        migrations.RemoveField(
            model_name='academic_years',
            name='grade_edit',
        ),
        migrations.RemoveField(
            model_name='academic_years',
            name='ignore_weekly_pal_dates',
        ),
        migrations.RemoveField(
            model_name='academic_years',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='academic_years',
            name='job_applicant_on',
        ),
        migrations.RemoveField(
            model_name='academic_years',
            name='week_plan',
        ),
        migrations.AddField(
            model_name='academic_year_semester',
            name='status_idf',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='general_settings.gsettingstatus'),
        ),
        migrations.AddField(
            model_name='academic_years',
            name='status_idf',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='general_settings.gsettingstatus'),
        ),
        migrations.AddField(
            model_name='semester',
            name='admission_on',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='allow_add_material_cover',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='allow_to_create_weekly_plan',
            field=models.IntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46'), ('47', '47'), ('48', '48'), ('49', '49'), ('50', '50'), ('51', '51'), ('52', '52'), ('53', '53'), ('54', '54'), ('55', '55'), ('56', '56'), ('57', '57'), ('58', '58'), ('59', '59'), ('60', '60')], null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='allow_to_view_weekly_plan',
            field=models.IntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46'), ('47', '47'), ('48', '48'), ('49', '49'), ('50', '50'), ('51', '51'), ('52', '52'), ('53', '53'), ('54', '54'), ('55', '55'), ('56', '56'), ('57', '57'), ('58', '58'), ('59', '59'), ('60', '60')], null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='edit_std_status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='grade_edit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='ignore_weekly_pal_dates',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='is_default',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='job_applicant_on',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='status_idf',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='general_settings.gsettingstatus'),
        ),
        migrations.AddField(
            model_name='semester',
            name='week_plan',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='year',
            name='status_idf',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='general_settings.gsettingstatus'),
        ),
    ]
