# Generated by Django 5.0.4 on 2024-05-14 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Finance_Fee_Collections',
            new_name='FinanceFeeCollections',
        ),
        migrations.RenameModel(
            old_name='Grade_Type_System',
            new_name='GradeTypeSystem',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='description',
            new_name='description_lng1',
        ),
        migrations.RenameField(
            model_name='registration_grade',
            old_name='additional_field_ids',
            new_name='additional_fields_array_ids',
        ),
        migrations.RenameField(
            model_name='registration_grade',
            old_name='enable_approval_system',
            new_name='elective_max_score',
        ),
        migrations.RenameField(
            model_name='registration_grade',
            old_name='is_active',
            new_name='elective_min_score',
        ),
        migrations.RenameField(
            model_name='registration_grade',
            old_name='age_limit_h',
            new_name='min_g_birthdate',
        ),
        migrations.RenameField(
            model_name='registration_grade',
            old_name='minimum_score',
            new_name='min_score',
        ),
        migrations.RenameField(
            model_name='stu_intial_class',
            old_name='name',
            new_name='name_lng1',
        ),
        migrations.RemoveField(
            model_name='events',
            name='title',
        ),
        migrations.RemoveField(
            model_name='registration_grade',
            name='age_limit_g',
        ),
        migrations.RemoveField(
            model_name='registration_grade',
            name='include_additional_details',
        ),
        migrations.RemoveField(
            model_name='registration_grade',
            name='max_elective',
        ),
        migrations.RemoveField(
            model_name='registration_grade',
            name='min_electives',
        ),
        migrations.RemoveField(
            model_name='registration_grade',
            name='subject_based_fee_collection',
        ),
        migrations.AddField(
            model_name='events',
            name='description_lng2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='title_lng1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='title_lng2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='registration_grade',
            name='active',
            field=models.SmallIntegerField(choices=[(1, 1), (0, 0)], default=1),
        ),
        migrations.AddField(
            model_name='registration_grade',
            name='is_allow_admission',
            field=models.SmallIntegerField(blank=True, choices=[(1, 1), (0, 0)], null=True),
        ),
        migrations.AddField(
            model_name='registration_grade',
            name='is_enable_approval_system',
            field=models.SmallIntegerField(blank=True, choices=[(1, 1), (0, 0)], null=True),
        ),
        migrations.AddField(
            model_name='registration_grade',
            name='is_include_additional_details',
            field=models.SmallIntegerField(blank=True, choices=[(1, 1), (0, 0)], null=True),
        ),
        migrations.AddField(
            model_name='registration_grade',
            name='is_subject_based_fee_colletion',
            field=models.SmallIntegerField(blank=True, choices=[(1, 1), (0, 0)], null=True),
        ),
        migrations.AddField(
            model_name='registration_grade',
            name='min_h_birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration_grade',
            name='school_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='general_settings.schools'),
        ),
        migrations.AddField(
            model_name='stu_class',
            name='name_lng1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stu_class',
            name='name_lng2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stu_class',
            name='school_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='general_settings.schools'),
        ),
        migrations.AddField(
            model_name='stu_intial_class',
            name='name_lng2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registration_grade',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='registration_grade',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='registration_grade',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_registration_grades_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registration_grade',
            name='grade_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_settings.grade'),
        ),
        migrations.AlterField(
            model_name='registration_grade',
            name='is_subject_based_registration',
            field=models.SmallIntegerField(blank=True, choices=[(1, 1), (0, 0)], null=True),
        ),
        migrations.AlterField(
            model_name='registration_grade',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='registration_grade',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_registration_grades_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='events',
            table='general_settings_events',
        ),
        migrations.AlterModelTable(
            name='financefeecollections',
            table='general_settings_finance_fee_collections',
        ),
        migrations.AlterModelTable(
            name='gradetypesystem',
            table='general_settings_grade_type_system',
        ),
        migrations.AlterModelTable(
            name='schools',
            table='general_settings_schools',
        ),
        migrations.CreateModel(
            name='GSettingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name_lng1', models.CharField(max_length=100)),
                ('name_lng2', models.CharField(max_length=100)),
                ('notes', models.TextField()),
                ('active', models.SmallIntegerField(choices=[(1, 1), (0, 0)])),
                ('ip_address', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_gsettingstatus_user', to=settings.AUTH_USER_MODEL)),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_settings.schools')),
                ('status_idf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_settings.gsettingstatus')),
                ('updated_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_gsettingstatus_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'general_settings_status',
            },
        ),
        migrations.AddField(
            model_name='registration_grade',
            name='status_idf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='general_settings.gsettingstatus'),
        ),
        migrations.CreateModel(
            name='ReceiverTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name_lng1', models.CharField(max_length=100)),
                ('name_lng2', models.CharField(max_length=100)),
                ('notes', models.TextField()),
                ('active', models.SmallIntegerField(choices=[(1, 1), (0, 0)])),
                ('ip_address', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_receiver_types_user', to=settings.AUTH_USER_MODEL)),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_settings.schools')),
                ('status_idf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_settings.gsettingstatus')),
                ('updated_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_receiver_types_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'general_settings_receiver_types',
            },
        ),
        migrations.CreateModel(
            name='StakeholdersTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name_lng1', models.CharField(max_length=100)),
                ('name_lng2', models.CharField(max_length=100)),
                ('notes', models.TextField()),
                ('active', models.SmallIntegerField(choices=[(1, 1), (0, 0)])),
                ('ip_address', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_stakeholders_types_user', to=settings.AUTH_USER_MODEL)),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_settings.schools')),
                ('status_idf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_settings.gsettingstatus')),
                ('updated_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_stakeholders_types_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'general_settings_stakeholders_types',
            },
        ),
        migrations.CreateModel(
            name='StudentCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name_lng1', models.CharField(max_length=100)),
                ('name_lng2', models.CharField(max_length=100)),
                ('notes', models.TextField()),
                ('active', models.SmallIntegerField(choices=[(1, 1), (0, 0)])),
                ('ip_address', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_student_categories_user', to=settings.AUTH_USER_MODEL)),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_settings.schools')),
                ('status_idf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_settings.gsettingstatus')),
                ('updated_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_student_categories_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'general_settings_student_categories',
            },
        ),
        migrations.AddField(
            model_name='stu_class',
            name='student_categories_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='general_settings.studentcategories'),
        ),
    ]
