# Generated by Django 5.0.4 on 2024-04-28 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0001_initial'),
        ('student', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantDocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name_lng1', models.CharField(blank=True, max_length=255, null=True)),
                ('doc_name_lng2', models.CharField(blank=True, max_length=255, null=True)),
                ('doc_desc_lng1', models.TextField(blank=True, null=True)),
                ('doc_desc_lng2', models.TextField(blank=True, null=True)),
                ('is_necessary', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='applicant_document_type_created_by', to=settings.AUTH_USER_MODEL)),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='applicant_document_type_school_id', to='general_settings.schools')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='applicant_document_type_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantDocumentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_file', models.FileField(blank=True, null=True, upload_to='files/applicant')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.applicant')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='applicant_document_attachment_created_by', to=settings.AUTH_USER_MODEL)),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='applicant_document_attachment_school_id', to='general_settings.schools')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='applicant_document_attachment_updated_by', to=settings.AUTH_USER_MODEL)),
                ('applicant_document_types_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.applicantdocumenttype')),
            ],
        ),
    ]
