# Generated by Django 5.0.4 on 2024-04-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_applicantdocumenttype_applicantdocumentattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantdocumenttype',
            name='doc_type',
            field=models.CharField(choices=[('PDF', 'PDF'), ('Image', 'Image'), ('Word', 'Word'), ('Excel', 'Excel'), ('PowerPoint', 'PowerPoint'), ('Text', 'Text'), ('Csv', 'Csv'), ('Presentation', 'Presentation'), ('Spreadsheet', 'Spreadsheet'), ('Document', 'Document'), ('Archive', 'Archive'), ('Audio', 'Audio'), ('Video', 'Video'), ('Others', 'Others')], default='Other', max_length=20),
        ),
    ]
