# Generated by Django 5.0.4 on 2024-04-29 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0001_initial'),
        ('student', '0004_alter_applicantdocumentattachment_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantdocumentattachment',
            name='school_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='applicant_document_attachment_school_id', to='general_settings.schools'),
        ),
    ]
