# Generated by Django 5.0.4 on 2024-04-29 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_applicantdocumentattachment_school_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_applicant_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_applicant_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicant_guardians',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_applicant_gur_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicant_guardians',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_applicant_gur_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicant_pervious_school_data',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_pervious_school_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicant_pervious_school_data',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_pervious_school_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicantdocumentattachment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='applicant_document_attachment_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicantdocumentattachment',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='applicant_document_attachment_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='imageapplicant',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_img_applicant_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='imageapplicant',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_img_applicant_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='status',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_status_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='status',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_status_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
