# Generated by Django 5.0.4 on 2024-05-12 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('general_settings', '0001_initial'),
        ('student', '0006_alter_applicant_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant_pervious_school_data',
            name='last_grade_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='general_settings.grade'),
        ),
        migrations.AlterField(
            model_name='applicant_pervious_school_data',
            name='last_year_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='academic.year'),
        ),
        migrations.AlterField(
            model_name='applicantdocumenttype',
            name='doc_type',
            field=models.CharField(choices=[('PDF', 'PDF'), ('Image', 'Image')], default='Other', max_length=20),
        ),
    ]
