# Generated by Django 5.0.4 on 2024-05-14 10:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('countries', '0001_initial'),
        ('general_settings', '0001_initial'),
        ('student', '0007_alter_applicant_pervious_school_data_last_grade_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Applicant_Pervious_School_Data',
            new_name='Applicant_Previous_School_Data',
        ),
        migrations.DeleteModel(
            name='imageApplicant',
        ),
    ]
