# Generated by Django 5.0.4 on 2024-05-14 10:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('countries', '0001_initial'),
        ('general_settings', '0001_initial'),
        ('student', '0008_rename_applicant_pervious_school_data_applicant_previous_school_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Applicant_Previous_School_Data',
            new_name='ApplicantPreviousSchoolData',
        ),
        migrations.AlterModelTable(
            name='applicantdocumentattachment',
            table='student_applicant_document_attachment',
        ),
        migrations.AlterModelTable(
            name='applicantdocumenttype',
            table='student_applicant_document_type',
        ),
        migrations.AlterModelTable(
            name='applicantpreviousschooldata',
            table='student_applicant_previous_school_data',
        ),
    ]
