# Generated by Django 5.0.4 on 2024-05-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_remove_applicant_status_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='status_order_by',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
