# Generated by Django 5.0.4 on 2024-05-28 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_status_status_order_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='status_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='applicant_status_id', to='student.status', to_field='status_order_by'),
        ),
    ]
