# Generated by Django 5.0.4 on 2024-05-26 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0002_rename_finance_fee_collections_financefeecollections_and_more'),
        ('usermgr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAdditionalFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='general_settings.schools')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='useradditionalfields', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_additional_fields',
            },
        ),
    ]
