# Generated by Django 5.0.4 on 2024-05-29 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('student', '0013_rename_evaluation_applicantpreviousschooldata_evaluvation'),
        ('usermgr', '0002_useradditionalfields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='nat_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='student.applicant'),
        ),
    ]
