# Generated by Django 5.0.4 on 2024-06-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermgr', '0003_alter_user_profile_nat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='nat_id',
            field=models.CharField(blank=True, default='000', max_length=14, null=True),
        ),
    ]
